### ISSUE TITLE
RNB templates for well-known color schemes

### ISSUE THREAD

**Issue by mroavi** [romainl/vim-rnb#5]
I was thinking that it would be very helpful to have RNB templates for well-known color schemes like:
- solarized
- onedark
- gruvbox
- dracula
- monokai
...

so that we could use them as ideal starting points rather than starting from a "blank" template. Could it be that these exist already and I am unaware of them?

**Comment by romainl** [comment]
Hi @mroavi, RNB wasn't used in the making of those colorschemes so I'm almost sure those templates don't exist.

This is something I won't do myself, but I could certainly consider pull requests to that effect.

**Comment by mroavi** [comment]
Thanks for the answer @romainl. On second thought, it would be just as useful to have example templates of any color scheme. It would be great if your repo could host a directory with a suite of example templates that people could quickly try to see if they accommodate their needs. If they do, then they could further refine them by tweaking colors, hi groups etc. This would speed up the design process a lot. It would be great if existing RNB users could send pull-requests with their designed templates.

I'm just leaving ideas out here on how to improve your tool which is actually very good already.

**Comment by romainl** [comment]
Yes, a `samples` directory with clones of popular colorschemes would probably be useful for new users but I can see from here how hard and time-consuming it will be to manage that directory, from creating the templates to keeping them in sync with upstream… which don't use RNB to begin with.

As I said before, I'm not against the idea of RNB users making PRs with their work but you have to keep in mind that RNB is a pretty *niche* project that is not used by a lot of people and when it is, it is not used for super popular colorschemes so, since I definitely won't clone popular colorschemes, I can't see that `samples` directory happening any time soon.

The closest approximation would be a section in the README or the wiki, with screenshots and links to individual projects.

**Comment by mroavi** [comment]
Yeah, I think I got your point. Maybe is too much work indeed for a niche project that is not used by a lot of people like you mention. Thanks for your time anyway.
